using UnityEngine;
using System.Threading;

namespace OutGame
{
    /// <summary>
    /// Implements the IOutConductor interface to allow the player to be affected by electrical traps.
    /// Handles the local physical shutdown, animation-to-ragdoll transition, and reports the death to the Game Manager.
    /// </summary>
    [RequireComponent(typeof(CharacterController))]
    public class OutPlayerConductor : MonoBehaviour, IOutConductor
    {
        [Header("Component References")]
        [SerializeField] private Animator m_animator;
        [SerializeField] private MxM.MxMAnimator m_mxmAnimator;
        [SerializeField] private OutLocomotionManager m_locomotionManager;

        private CharacterController m_characterController;
        private Rigidbody[] m_boneRigidbodies;

        [Header("MxM Events")]
        [SerializeField] private MxM.MxMEventDefinition m_electrocutedEvent;

        private void Awake()
        {
            m_characterController = GetComponent<CharacterController>();

            if (m_locomotionManager == null)
                m_locomotionManager = GetComponent<OutLocomotionManager>();

            if (m_animator == null)
                m_animator = GetComponentInChildren<Animator>();

            if (m_mxmAnimator == null)
                m_mxmAnimator = GetComponentInChildren<MxM.MxMAnimator>();

            InitializeRagdoll();
        }

        private void InitializeRagdoll()
        {
            // Grab all rigidbodies in the children (the bones generated by the Ragdoll Wizard)
            m_boneRigidbodies = GetComponentsInChildren<Rigidbody>();

            foreach (Rigidbody rb in m_boneRigidbodies)
            {
                // Skip the main root rigidbody or character controller level
                if (rb.gameObject == this.gameObject) continue;

                // Force the bones to follow the animation without calculating physics yet
                rb.isKinematic = true;
            }
        }

        public void OnElectrocuted(Transform attachPoint)
        {
            OutLogger.Log("<color=orange>[OutPlayerConductor]</color> Player stepped into a Spark Trap!");

            // 1. Strip player control
            DisablePlayerLocomotion();

            // 2. Snap to the trap's execution point
            if (attachPoint != null)
            {
                transform.position = attachPoint.position;
                transform.rotation = attachPoint.rotation;
            }
            else
            {
                OutLogger.LogWarning("[OutPlayerConductor] Trap attach point is null. Skipping physical snap.");
            }

            // 3. Trigger local death feedback and start async ragdoll sequence
            if (m_mxmAnimator != null && m_electrocutedEvent != null)
            {
                m_mxmAnimator.BeginEvent(m_electrocutedEvent);
                _ = HandleDeathSequenceAsync();
            }
        }

        private async Awaitable HandleDeathSequenceAsync()
        {
            // Wait a frame to ensure the Animator registers the trigger
            await Awaitable.NextFrameAsync(destroyCancellationToken);

            while (m_mxmAnimator.IsEventPlaying)
            {
                if (destroyCancellationToken.IsCancellationRequested) return;
                await Awaitable.NextFrameAsync(destroyCancellationToken);
            }

            // Hand over to physics and broadcast game over
            EnableRagdoll();

            await Awaitable.WaitForSecondsAsync(1f, destroyCancellationToken);

            TriggerFailure();
            DisableEverything();
        }

        private void EnableRagdoll()
        {
            // Turn off the animators so they stop forcing bone positions
            if (m_animator != null) m_animator.enabled = false;
            if (m_mxmAnimator != null) m_mxmAnimator.enabled = false;

            foreach (Rigidbody rb in m_boneRigidbodies)
            {
                if (rb.gameObject == this.gameObject) continue;

                // Give control back to the physics engine
                rb.isKinematic = false;

                // Apply a tiny bit of random torque so the player slumps naturally
                rb.AddTorque(new Vector3(
                    Random.Range(-2f, 2f),
                    Random.Range(-2f, 2f),
                    Random.Range(-2f, 2f)
                ), ForceMode.Impulse);
            }
        }

        private void TriggerFailure()
        {
            if (OutGameManager.Instance != null)
            {
                OutGameManager.Instance.TriggerSylvianFailed("Electrocuted by Spark Trap");
            }
            else
            {
                OutLogger.LogError("[OutPlayerConductor] OutGameManager Instance is missing! Cannot trigger global failure state.");
            }
        }

        private void DisablePlayerLocomotion()
        {
            // Lock out Unity Input System mappings
            if (OutInputManager.Instance != null)
            {
                OutInputManager.Instance.SetGameplayInput(false);
            }

            // Disable Character Controller so physics ignore the corpse
            if (m_characterController != null)
                m_characterController.enabled = false;

            // Shut down MxM Locomotion logic
            if (m_locomotionManager != null)
                m_locomotionManager.enabled = false;
        }

        private void DisableEverything()
        {
            foreach (var comp in GetComponents<MonoBehaviour>())
            {
                if (comp != this)
                    comp.enabled = false;
            }
        }
    }
}
